### ISSUE TITLE
Type information is lost in loops

### ISSUE THREAD

**Issue by bendem** [bjansen/pebble-intellij#37]
When writing stuff like

```twig
{# @pebvariable name="movements" type="org.jooq.Result<be.lghs.accounting.model.tables.records.MovementsRecord>" #}

{% for movement in movements %}
    {{ movement.<autocomplete> }}
{% endfor %}
```

the `movement` is of type `Object` and there is no type completion (not even `Object`'s methods).

**Comment by bjansen** [comment]
The variable is currently always considered as an `Object`, but I could improve that since the looped expression has to be an `Iterable<>` of some sort.

**Comment by ashokgelal** [comment]
@bjansen Any update on this?

**Comment by bjansen** [comment]
No sorry, I haven't had time to work on this yet. Now that the number of people annoyed by this bug has doubled, I'll prioritize it :)

**Comment by bjansen** [comment]
I think I got it working, could you please try this build?

[pebble-intellij.zip](https://github.com/bjansen/pebble-intellij/files/4112075/pebble-intellij.zip)

**Comment by bendem** [comment]
It works for normal context, I don't get any information for string interpolation but that's still much better. Thanks a bunch!

**Comment by bjansen** [comment]
Could you give me an example for the string interpolation thing?

**Comment by bendem** [comment]
![image](https://user-images.githubusercontent.com/2681677/73122551-9d924d80-3f86-11ea-86b5-2fab1616a17a.png)
![image](https://user-images.githubusercontent.com/2681677/73122589-0b3e7980-3f87-11ea-94af-658f7e2e743c.png)

**Comment by bendem** [comment]
Source is available here: https://github.com/LgHS/accounting/blob/ecd6694b5bb0b2de588932ca3358fdcfad5d925c/src/main/resources/templates/app/movements/list.peb#L31-L33

**Comment by ashokgelal** [comment]
This works! Even on the latest 2020.1 EAP. Thank you!!

**Comment by bendem** [comment]
After using this for a while, I hit this stacktrace:

```
java.lang.IllegalStateException: node.treeParent must not be null
	at com.github.bjansen.intellij.pebble.psi.PsiElementFactory.createElement(PsiElementFactory.kt:50)
	at com.github.bjansen.intellij.pebble.psi.PebbleParserDefinition.createElement(PebbleParserDefinition.kt:136)
	at com.intellij.psi.impl.source.tree.CompositeElement.createPsiNoLock(CompositeElement.java:722)
	at com.intellij.psi.impl.source.tree.CompositeElement.getPsi(CompositeElement.java:709)
	at com.intellij.psi.impl.DiffLog.getPsi(DiffLog.java:207)
	at com.intellij.psi.impl.DiffLog.access$500(DiffLog.java:27)
	at com.intellij.psi.impl.DiffLog$InsertEntry.doActualPsiChange(DiffLog.java:174)
	at com.intellij.psi.impl.DiffLog.performActualPsiChange(DiffLog.java:44)
	at com.intellij.psi.impl.DiffLog$1.runInner(DiffLog.java:270)
	at com.intellij.pom.impl.PomTransactionBase.run(PomTransactionBase.java:46)
	at com.intellij.pom.core.impl.PomModelImpl.lambda$null$1(PomModelImpl.java:151)
	at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:564)
	at com.intellij.pom.core.impl.PomModelImpl.lambda$runTransaction$2(PomModelImpl.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:186)
	at com.intellij.pom.core.impl.PomModelImpl.runTransaction(PomModelImpl.java:135)
	at com.intellij.psi.impl.DiffLog.lambda$doActualPsiChange$0(DiffLog.java:267)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.lambda$performActionWithFormatterDisabled$6(CodeStyleManagerImpl.java:696)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.disablePostprocessFormattingInside(PostprocessReformattingAspect.java:108)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.lambda$performActionWithFormatterDisabled$8(CodeStyleManagerImpl.java:725)
	at com.intellij.formatting.FormatterImpl.runWithFormattingDisabled(FormatterImpl.java:682)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.performActionWithFormatterDisabled(CodeStyleManagerImpl.java:723)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.performActionWithFormatterDisabled(CodeStyleManagerImpl.java:695)
	at com.intellij.psi.impl.DiffLog.doActualPsiChange(DiffLog.java:255)
	at com.intellij.psi.impl.DocumentCommitThread.lambda$doCommit$8(DocumentCommitThread.java:704)
	at com.intellij.psi.impl.PsiDocumentManagerBase.commitToExistingPsi(PsiDocumentManagerBase.java:416)
	at com.intellij.psi.impl.PsiDocumentManagerBase.lambda$finishCommitInWriteAction$4(PsiDocumentManagerBase.java:388)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:191)
	at com.intellij.psi.impl.PsiDocumentManagerBase.finishCommitInWriteAction(PsiDocumentManagerBase.java:383)
	at com.intellij.psi.impl.PsiDocumentManagerImpl.finishCommitInWriteAction(PsiDocumentManagerImpl.java:130)
	at com.intellij.psi.impl.PsiDocumentManagerBase$1.run(PsiDocumentManagerBase.java:344)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:885)
	at com.intellij.psi.impl.PsiDocumentManagerBase.finishCommit(PsiDocumentManagerBase.java:351)
	at com.intellij.psi.impl.DocumentCommitThread.lambda$createFinishCommitInEDTRunnable$5(DocumentCommitThread.java:490)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:83)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:107)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:441)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:908)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:424)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

Following exceptions happened soon after this one, most probably they are induced.


2020-01-26T19:11:09.970
java.lang.IllegalStateException: node.treeParent must not be null
	at com.github.bjansen.intellij.pebble.psi.PsiElementFactory.createElement(PsiElementFactory.kt:50)
	at com.github.bjansen.intellij.pebble.psi.PebbleParserDefinition.createElement(PebbleParserDefinition.kt:136)
	at com.intellij.psi.impl.source.tree.CompositeElement.createPsiNoLock(CompositeElement.java:722)
	at com.intellij.psi.impl.source.tree.CompositeElement.getPsi(CompositeElement.java:709)
	at com.intellij.psi.impl.DiffLog.getPsi(DiffLog.java:207)
	at com.intellij.psi.impl.DiffLog.access$500(DiffLog.java:27)
	at com.intellij.psi.impl.DiffLog$InsertEntry.doActualPsiChange(DiffLog.java:174)
	at com.intellij.psi.impl.DiffLog.performActualPsiChange(DiffLog.java:44)
	at com.intellij.psi.impl.DiffLog$1.runInner(DiffLog.java:270)
	at com.intellij.pom.impl.PomTransactionBase.run(PomTransactionBase.java:46)
	at com.intellij.pom.core.impl.PomModelImpl.lambda$null$1(PomModelImpl.java:151)
	at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:564)
	at com.intellij.pom.core.impl.PomModelImpl.lambda$runTransaction$2(PomModelImpl.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:186)
	at com.intellij.pom.core.impl.PomModelImpl.runTransaction(PomModelImpl.java:135)
	at com.intellij.psi.impl.DiffLog.lambda$doActualPsiChange$0(DiffLog.java:267)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.lambda$performActionWithFormatterDisabled$6(CodeStyleManagerImpl.java:696)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.disablePostprocessFormattingInside(PostprocessReformattingAspect.java:108)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.lambda$performActionWithFormatterDisabled$8(CodeStyleManagerImpl.java:725)
	at com.intellij.formatting.FormatterImpl.runWithFormattingDisabled(FormatterImpl.java:682)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.performActionWithFormatterDisabled(CodeStyleManagerImpl.java:723)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.performActionWithFormatterDisabled(CodeStyleManagerImpl.java:695)
	at com.intellij.psi.impl.DiffLog.doActualPsiChange(DiffLog.java:255)
	at com.intellij.psi.impl.DocumentCommitThread.lambda$doCommit$8(DocumentCommitThread.java:704)
	at com.intellij.psi.impl.PsiDocumentManagerBase.commitToExistingPsi(PsiDocumentManagerBase.java:416)
	at com.intellij.psi.impl.PsiDocumentManagerBase.lambda$finishCommitInWriteAction$4(PsiDocumentManagerBase.java:388)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:191)
	at com.intellij.psi.impl.PsiDocumentManagerBase.finishCommitInWriteAction(PsiDocumentManagerBase.java:383)
	at com.intellij.psi.impl.PsiDocumentManagerImpl.finishCommitInWriteAction(PsiDocumentManagerImpl.java:130)
	at com.intellij.psi.impl.PsiDocumentManagerBase$1.run(PsiDocumentManagerBase.java:344)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:885)
	at com.intellij.psi.impl.PsiDocumentManagerBase.finishCommit(PsiDocumentManagerBase.java:351)
	at com.intellij.psi.impl.DocumentCommitThread.lambda$createFinishCommitInEDTRunnable$5(DocumentCommitThread.java:490)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:83)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:107)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:441)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:908)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:424)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by bjansen** [comment]
Yep I've seen it too, I'm going to fix it. Thanks for the feedback!

**Comment by bjansen** [comment]
New build with all the problems fixed:
[pebble-intellij.zip](https://github.com/bjansen/pebble-intellij/files/4117139/pebble-intellij.zip)

**Comment by awallat** [comment]
I also tried your fix, but unfortunately it didn't work for me. I get suggestions, but not the correct ones. I have something like this:

```
{% for item in car.parts %}
    {{item.label}}
{% endfor %}
```

And the model:
```
public class Car {
    public List<Part> parts = new ArrayList<>();
}
```

The autocomplete values for item however are:
`equals, hashCode, toString, notify, wait, ...`
instead of the ones defined in my model class "Part". It seems as if the List is not recognized correctly and String class is used.

**Comment by ashokgelal** [comment]
@awallat Just to be clear, you did add {# @pebvariable ... #} at the top right?

This is what I added and got it working: https://github.com/alpas/fireplace/blob/master/src/main/resources/templates/project_list.peb#L1

**Comment by bjansen** [comment]
@ashokgelal I added a fix in master to support fields (like `public List<Part> parts`) in `for` tags. I was able to reproduce @awallat's issue.

**Comment by awallat** [comment]
@bjansen Thanks a lot for the quick fix.

I just found another little problem however. If I have a private property "label" in my model class "Part" with getter and setter, then Intellij complains about:

> Attribute [label] of [test.car.Part] does not exist or can not be accessed

If I however remove the setter then there's no problem.
```java
public class Part {
  private String label;

  public String getLabel() {
    return this.label;
  }

  public void setLabel(String label) {
    this.label = label;
  }
}
```

**Comment by decebals** [comment]
I have a problem related to issue:
![image](https://user-images.githubusercontent.com/1248311/86368666-190ad000-bc86-11ea-801d-efcaa3833776.png)

I am using Idea IntelliJ 2020.1.2 with Pebble plugin 0.6.

**Comment by bendem** [comment]
Unless I'm  mistaken, the fix has never been released thus why you still see the problem.

**Comment by decebals** [comment]
@bendem Probably solution is to download and use the version from zip available at https://github.com/bjansen/pebble-intellij/issues/37#issuecomment-578729493.

@bjansen Can you help us with a release, please?

**Comment by bjansen** [comment]
@awallat your last problem was also fixed.

@bendem @decebals I just pushed version 0.7 to the plugins repository. As usual:
> The plugin has been submitted for moderation. The request will be processed within two business days.
