### ISSUE TITLE
Bug in Pycharm 2019.2.2

### ISSUE THREAD

**Issue by KaterinaHejtmankova** [bjansen/pebble-intellij#38]
Hello, I have NoClassDefFoundError in Pycharm 2019.2.2 with pebble plugin version 0.5. How can I fix it? Thanks!
`java.lang.NoClassDefFoundError: com/intellij/psi/PsiTypeCodeFragment$IncorrectTypeException
	at com.github.bjansen.intellij.pebble.psi.PebbleComment.<clinit>(PebbleComment.kt)
	at com.github.bjansen.intellij.pebble.lang.PebbleAstFactory.createComment(PebbleAstFactory.kt:11)
	at com.intellij.core.CoreASTFactory.createLeaf(CoreASTFactory.java:56)
	at com.intellij.lang.ASTFactory.leaf(ASTFactory.java:97)
	at com.intellij.lang.impl.PsiBuilderImpl.createLeaf(PsiBuilderImpl.java:1751)
	at com.intellij.lang.impl.PsiBuilderImpl.insertLeaves(PsiBuilderImpl.java:1268)
	at com.intellij.lang.impl.PsiBuilderImpl.bind(PsiBuilderImpl.java:1217)
	at com.intellij.lang.impl.PsiBuilderImpl.buildTree(PsiBuilderImpl.java:938)
	at com.intellij.lang.impl.PsiBuilderImpl.getTreeBuilt(PsiBuilderImpl.java:924)
	at org.antlr.intellij.adaptor.parser.ANTLRParserAdaptor.parse(ANTLRParserAdaptor.java:82)
	at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:75)
	at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:53)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.lambda$ensureParsed$0(LazyParseableElement.java:198)
	at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:564)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:197)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:246)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:40)
	at com.intellij.formatting.templateLanguages.TemplateLanguageBlock.buildChildren(TemplateLanguageBlock.java:63)
	at com.intellij.psi.formatter.common.AbstractBlock.getSubBlocks(AbstractBlock.java:47)
	at com.intellij.psi.formatter.common.NewLineBlocksIterator.pushAll(NewLineBlocksIterator.java:135)
	at com.intellij.psi.formatter.common.NewLineBlocksIterator.next(NewLineBlocksIterator.java:105)
	at com.intellij.psi.codeStyle.autodetect.FormatterBasedLineIndentInfoBuilder.getBlocksStartingNewLine(FormatterBasedLineIndentInfoBuilder.java:130)
	at com.intellij.psi.codeStyle.autodetect.FormatterBasedLineIndentInfoBuilder.build(FormatterBasedLineIndentInfoBuilder.java:54)
	at com.intellij.psi.codeStyle.autodetect.IndentOptionsDetectorImpl.calcLineIndentInfo(IndentOptionsDetectorImpl.java:100)
	at com.intellij.psi.codeStyle.autodetect.IndentOptionsDetectorImpl.getIndentOptionsAdjuster(IndentOptionsDetectorImpl.java:65)
	at com.intellij.psi.codeStyle.DetectAndAdjustIndentOptionsTask.performInReadAction(DetectAndAdjustIndentOptionsTask.java:86)
	at com.intellij.openapi.progress.util.ReadTask.lambda$runBackgroundProcess$0(ReadTask.java:66)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:936)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runUnderProgress$4(ProgressIndicatorUtils.java:231)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$3(CoreProgressManager.java:185)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:185)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runUnderProgress(ProgressIndicatorUtils.java:229)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$100(ProgressIndicatorUtils.java:37)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:180)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:207)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$100(BoundedTaskExecutor.java:29)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.lambda$run$0(BoundedTaskExecutor.java:185)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:208)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:181)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: com.intellij.psi.PsiTypeCodeFragment$IncorrectTypeException PluginClassLoader[com.github.bjansen.intellij.pebble, 0.5] com.intellij.ide.plugins.cl.PluginClassLoader@22a15175
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:75)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 49 more`

**Comment by bjansen** [comment]
Hi there. The plugin needs Java support to work properly. That's something I forgot to specify in the plugin metadata, that I fixed in version 0.6. You can see that the current version [now depends on ` com.intellij.modules.java`](https://plugins.jetbrains.com/plugin/9407-pebble/update/65791).

So while it's technically possible to install version < 0.6 in IDEs other than IDEA/Android Studio, the plugin will crash.

I suppose you're trying to use this plugin for another templating engine that has a syntax similar to Pebble's?

**Comment by bjansen** [comment]
Hey @KaterinaHejtmankova, were you trying to edit Jinja templates with the pebble plugin?
